name: "Code quality visualizer"
author: "Keisuke Shima"
description: "Measure code metrics and generate result page"
branding:
  icon: "activity"
  color: "blue"

runs:
  using: "composite"
  steps:
    - run: |
        echo "GITHUB_ACTION_PATH is ${GITHUB_ACTION_PATH}"
        ls -l ${GITHUB_ACTION_PATH}
        echo "github.action_path is ${{ github.action_path }}"
        echo "GITHUB_WORKSPACE is ${GITHUB_WORKSPACE}"
        ls -l ${GITHUB_WORKSPACE}
        echo "Workspace is ${{ github.workspace }}"
        apt-get update
        apt-get install -y lcov git python-is-python3 python3-pip hugo
        rosdep update
        rosdep install -y --from-paths . --ignore-src --rosdistro foxy
        pip3 install jinja2 bs4 pandas plotly
        echo "Creating timestamp to ${GITHUB_WORKSPACE}/timestamp.txt"
        date -u '+%Y%m%d_%H%M%S' > ${GITHUB_WORKSPACE}/timestamp.txt
        echo "Output directory is ${GITHUB_WORKSPACE}/artifacts"
        mkdir ${GITHUB_WORKSPACE}/artifacts
        echo "Run coverage.sh"
        ${GITHUB_ACTION_PATH}/scripts/coverage.sh ${GITHUB_WORKSPACE} ${GITHUB_WORKSPACE}/timestamp.txt && mv ${GITHUB_WORKSPACE}/lcov ${GITHUB_WORKSPACE}/artifacts/
        echo "Run lizard.sh"
        ${GITHUB_ACTION_PATH}/scripts/lizard.sh ${GITHUB_WORKSPACE} ${GITHUB_WORKSPACE}/timestamp.txt && mv ${GITHUB_WORKSPACE}/lizard_result ${GITHUB_WORKSPACE}/artifacts/
        TIMESTAMP=$(cat ${GITHUB_WORKSPACE}/timestamp.txt)
        mkdir -p ${GITHUB_WORKSPACE}/artifacts/metrics/$TIMESTAMP
        echo "Run scraping.py"
        python3 scripts/scraping.py --lcov_dir=${GITHUB_WORKSPACE}/artifacts/lcov/$TIMESTAMP/ --lizard_dir=${GITHUB_WORKSPACE}/artifacts/lizard_result/$TIMESTAMP/ --output_dir=${GITHUB_WORKSPACE}/artifacts/metrics/$TIMESTAMP/
        ln -nfrs ${GITHUB_WORKSPACE}/artifacts/lcov/$TIMESTAMP ${GITHUB_WORKSPACE}/artifacts/lcov/latest
        ln -nfrs ${GITHUB_WORKSPACE}/artifacts/lizard_result/$TIMESTAMP ${GITHUB_WORKSPACE}/artifacts/lizard_result/latest
        ln -nfrs ${GITHUB_WORKSPACE}/artifacts/metrics/$TIMESTAMP ${GITHUB_WORKSPACE}/artifacts/metrics/latest
        echo "Run main.py"
        python scripts/main.py --input-dir=${GITHUB_WORKSPACE}/artifacts/metrics/ --hugo-root-dir=${GITHUB_ACTION_PATH}/example/hugo-site/ --hugo-template-dir=${GITHUB_ACTION_PATH}/template/hugo/ --lcov-result-path=${GITHUB_WORKSPACE}/artifacts/lcov/latest/ --lizard-result-path=${GITHUB_WORKSPACE}/artifacts/lizard_result/latest/
        echo "Copy artifacts"
        cp -r ${GITHUB_WORKSPACE}/artifacts/lcov/ ${GITHUB_ACTION_PATH}/example/hugo-site
        cp -r ${GITHUB_WORKSPACE}/artifacts/lizard_result/ ${GITHUB_ACTION_PATH}/example/hugo-site
        cd ${GITHUB_ACTION_PATH}/example/hugo-site && hugo -d ${GITHUB_WORKSPACE}/public
      shell: bash
