name: pre-commit

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - name: Install clang-format-11
      run: sudo apt-get update && sudo apt-get install -y clang-format-11
    - uses: pre-commit/action@v3.0.0
