name: pre-commit

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3.1.0
    - name: Install clang-format-10
      run: sudo apt-get update && sudo apt-get install -y clang-format-10
    - uses: pre-commit/action@v2.0.3
