name: Push document

on:
  push:
    branches: main

jobs:
  generate-document:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: doc

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Create static page
        run: python3 scripts/main.py --input_dir=${GITHUB_WORKSPACE}/doc/metrics/ --hugo_root_dir=${GITHUB_WORKSPACE}/example/hugo-site/ --hugo_template_dir=${GITHUB_WORKSPACE}/template/hugo/

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.83.1'

      - name: Generate pages
        run: |
          cd example/hugo-site
          hugo --minify -d ${GITHUB_WORKSPACE}/public/site

      - name: Deploy measurement result page to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: true
