
name: pytest

on:
  push:

jobs:
  pytest:
    name: Run tests with pytest
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup ROS to use colcon commands
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pipenv
          pipenv requirements > requirement.txt
          pip install -r requirement.txt
          colcon mixin add default https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
          colcon mixin update default

      - name: Import vcs repo
        run: |
          vcs import . < ros-metrics-reporter-humble.repos

      - name: Run tests
        run: |
          pytest -m "not local" tests/
