
name: pytest

on:
  push:

jobs:
  pytest:
    name: Run tests with pytest
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv lock
          pipenv sync --dev

      - name: Setup ROS to use colcon commands
        uses: ros-tooling/setup-ros@v0.3
        with:
          required-ros-distributions: humble

      - name: Import vcs repo
        run: |
          vcs import . < ros-metrics-reporter-humble.repos

      - name: Run tests
        run: |
          pipenv run pytest
