
name: Check spelling

on:
  pull_request:

jobs:
  spellcheck:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Retrieve spell check dictionary
        run: |
          curl --silent --show-error \
            --output .github/workflows/.cspell.json \
            https://raw.githubusercontent.com/tier4/autoware-spell-check-dict/main/cspell/.cspell.json
      - uses: streetsidesoftware/cspell-action@v5
        with:
          config: ".github/workflows/.cspell.json"
